language: php
sudo: required
dist: trusty
group: edge

php:
  - 5.6
  - 7.2
  - 7.3
  - 7.4

sudo: false

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -u root -e 'create database laravelchat;'
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate:install --env=testing --no-interaction
  - composer dump-autoload
  - sudo chgrp -R www-data storage bootstrap/cache
  - sudo chmod -R ug+rwx storage bootstrap/cache
  - php artisan migrate

script: vendor/bin/phpunit
